/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tk.perryma.circuitplaygroundfirmata4j.ui;

import java.awt.Color;
import java.awt.Graphics;
import org.firmata4j.Pin;

/**
 *
 * @author bdahl
 */
public class AnalogInput extends PinPanel {

    private final Pin pin;
    
    /**
     * Creates new DigitalInput Pin Display
     * @param pin
     *          The pin whose data is being displayed
     */
    public AnalogInput(Pin pin) {
        this.pin = pin;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueDisp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        valueDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueDisp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valueDisp.setText("Value: ##");
        valueDisp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valueDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valueDisp, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void showValue(long value) {
        valueDisp.setText("Value: " + value);
        System.out.println("Pin " + pin.getIndex() + " " + value);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel valueDisp;
    // End of variables declaration//GEN-END:variables
}
