/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tk.perryma.circuitplaygroundfirmata4j.ui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import tk.perryma.circuitplaygroundfirmata4j.CircuitPlayground;

/**
 *
 * @author bdahl
 */
public class BoardDisplay extends javax.swing.JPanel {
    private Image background = null;
    boolean leftButton;
    boolean rightButton;
    boolean slideSwitch;
    LEDButton led;
    ColorButton[] neoPixel;
    
    /**
     * Creates a new inactive BoardDisplay
     * 
     */
    public BoardDisplay() {
        this(null);
    }
    
    /**
     * Creates new BoardDisplay
     * @param cp 
     *          The CircuitPlayground to connect to
     */
    public BoardDisplay(CircuitPlayground cp) {
        try {
            // Set the background
            background = ImageIO.read(this.getClass().getResource("/img/circuitPlayground.png"));
            
            if (cp != null) {
                // Initialize button states
                leftButton = cp.leftButtonPressed();
                rightButton = cp.rightButtonPressed();
                slideSwitch = cp.switchOn();
            }
        }
        catch (IOException e) {}
            
        initComponents();
        
        // Initialize LED display
        led = new LEDButton();
        led.setLocation(479, 82);
        led.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                led.toggle();
                
                try {
                    if (cp != null) {
                        cp.setLED(led.isOn());
                    }
                }
                catch (IOException ex) {
                    JOptionPane.showMessageDialog(led, 
                        "Could not toggle LED.", ex.toString(),
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        add(led);
        
        // Initialize NeoPixel colors
        neoPixel = new ColorButton[10];
        for (int i = 0; i < neoPixel.length; i++) {
            neoPixel[i] = new ColorButton(i, Color.BLACK);
            add(neoPixel[i]);
            neoPixel[i].addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    ColorButton source = ((ColorButton)e.getSource());
                    
                    Color c = JColorChooser.showDialog(source, 
                            "Choose a color", source.getColor());
                    
                    if (c != null) {
                        try {
                            source.setColor(c);
                            
                            if (cp != null) {
                                cp.setNeoPixelColor(source.getNum(), c);
                                cp.showNeoPixels();
                            }
                        }
                        catch (IOException ex) {
                            JOptionPane.showMessageDialog(source, 
                                    "Could not change color", ex.toString(),
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            });
        }
        neoPixel[0].setLocation(258, 169);
        neoPixel[1].setLocation(174, 259);
        neoPixel[2].setLocation(142, 377);
        neoPixel[3].setLocation(174, 501);
        neoPixel[4].setLocation(267, 587);
        neoPixel[5].setLocation(500, 583);
        neoPixel[6].setLocation(590, 490);
        neoPixel[7].setLocation(618, 381);
        neoPixel[8].setLocation(588, 262);
        neoPixel[9].setLocation(498, 170);
     
        if (cp != null) {
            
        // Add listeners to autoupdate button displays
            cp.addLeftButtonListener((val) -> {
                leftButton = val;
                showLeftButton(null);
            });

            cp.addRightButtonListener((val) -> {
                rightButton = val;
                showRightButton(null);
            });

            cp.addSwitchListener((val) -> {
                slideSwitch = val;
                showSlideSwitch(null);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(800, 800));
        setMinimumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(800, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        g.drawImage(background, 0, 0, this);
        
        showLeftButton(g);
        showRightButton(g);
        showSlideSwitch(g);
    }

    
    private void showLeftButton(Graphics g) {
        boolean dispose = false;
        if (g == null) {
            g = this.getGraphics();
            dispose = true;
        }
        
        if (leftButton) {
            g.setColor(Color.GREEN);
        }
        else {
            g.setColor(Color.BLACK);
        }
        g.fillOval(238, 367, 42, 42);
        
        if (dispose) {
            g.dispose();
        }
    }

    private void showRightButton(Graphics g) {
        boolean dispose = false;
        if (g == null) {
            g = this.getGraphics();
            dispose = true;
        }
        
        if (rightButton) {
            g.setColor(Color.GREEN);
        }
        else {
            g.setColor(Color.BLACK);
        }
        g.fillOval(520, 367, 42, 42);
        
        if (dispose) {
            g.dispose();
        }
    }

    private void showSlideSwitch(Graphics g) {
        boolean dispose = false;
        if (g == null) {
            g = this.getGraphics();
            dispose = true;
        }
        
        if (slideSwitch) {
            g.setColor(Color.GREEN);
        }
        else {
            g.setColor(Color.BLACK);
        }
        g.fillRect(379, 522, 41, 14);
        
        if (dispose) {
            g.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
