/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tk.perryma.circuitplaygroundfirmata4j.ui;

import java.io.IOException;
import javax.swing.JOptionPane;
import org.firmata4j.Pin;

/**
 *
 * @author bdahl
 */
public class DigitalOutput extends PinPanel {

    private final Pin pin;

    /**
     * Creates new DigitalOutput panel
     *
     * @param pin The pin this panel should control
     */
    public DigitalOutput(Pin pin) {
        this.pin = pin;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputToggle = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        outputToggle.setText("Off");
        outputToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputToggleActionPerformed(evt);
            }
        });
        add(outputToggle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void outputToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputToggleActionPerformed
        long output = outputToggle.isSelected() ? 1 : 0;
        
        try {
            pin.setValue(output);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null,
                    "Could not communicate with Circuit Playground",
                    "Communications Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_outputToggleActionPerformed

    @Override
    public void showValue(long value) {
        outputToggle.setSelected(value != 0);
        
        if (outputToggle.isSelected()) {
            outputToggle.setText("On");
        }
        else {
            outputToggle.setText("Off");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton outputToggle;
    // End of variables declaration//GEN-END:variables
}
